-- Add Annual Leave columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboard_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS annual_leave_total NUMERIC DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS annual_leave_used NUMERIC DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_reset_date DATE;

-- Create Annual Leave Logs table
CREATE TABLE IF NOT EXISTS annual_leave_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  year INTEGER, -- e.g., 0 (for <1yr), 1 (1st year), etc.
  action TEXT CHECK (action IN ('grant', 'reset')),
  days_change NUMERIC,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies for annual_leave_logs
ALTER TABLE annual_leave_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can view all logs"
ON annual_leave_logs FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM users WHERE id = auth.uid() AND role IN ('manager', 'super_admin')
  )
);

CREATE POLICY "Users can view own logs"
ON annual_leave_logs FOR SELECT
USING (user_id = auth.uid());
